### ISSUE TITLE
Unable to find the `.trex` file

### ISSUE THREAD

**Issue by herambgadgil** [rstudio/shinytableau#10]
Hello,

I am excited to try this package! 

Going through the documentation - https://rstudio.github.io/shinytableau/articles/shinytableau.html, I couldn't find the `.trex` file it mentions. I looked on the package's GitHub README doc and Tableau website. 

Not sure if this is missing or I am looking in wrong place. 

Thanks!
Heramb

**Comment by denisabd** [comment]
Hi Heramb, you need to run the App.R file and you will see the dialog window from which you can download the .trex file. Try to replicate the example from this vignette https://rstudio.github.io/shinytableau/articles/helloworld.html

Denis

**Comment by herambgadgil** [comment]
I am getting a following error while running the template app
```
Error: 'bs_add_layers' is not an exported object from 'namespace:bootstraplib'
```
I checked in `rstudio/bootstraplib` and `bs_add_layers` is not present in the `NAMESPACE` file. Should I raise an issue there?

Thanks!
Heramb

**Comment by denisabd** [comment]
Hey, I am just a fellow package user as you are :) but I think you should, (I am getting the same issue as you do now). Maybe you can close this and raise the new one. Don't forget to add sessionInfo().

Denis

**Comment by herambgadgil** [comment]
Yes. I will do that. 

-Heramb
